CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS generated_ids (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    RandomID VARCHAR(255) NOT NULL,
    GeneratedDateTime DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);